# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('short_description', models.CharField(db_index=True, max_length=255)),
                ('text', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
